Project_MVC5/Controllers/Test_reportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using System.IO;

namespace Project_MVC5.Controllers
{
    public class Test_reportController : Controller
    {
        // GET: Test_report
        public ActionResult Index()
        {
            return View();
        }
        public void ShowSimple()
        {
            using (ReportDocument rptH = new ReportDocument())
            {
                rptH.FileName = Server.MapPath("~/Reports/Report_SalesDaily.rpt");
                rptH.Load(Path.Combine(Server.MapPath("~/Reports/Report_SalesDaily.rpt")));
                rptH.ExportToHttpResponse(ExportFormatType.PortableDocFormat, System.Web.HttpContext.Current.Response, false, "crReport");
            }
        }
    }
}

Project_MVC5/Views/Test_report/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_SalesLayout.cshtml";
}

<h2>Index</h2>
<a href="@Url.Action("ShowSimple","Test_report")">Export Report</a>
<h2>Report from MVC</h2>
<script type="text/javascript">
function SimpleInNewWin() {
    window.open("../Test_report/ShowSimple");// calling action
}
 
</script>
<h2>Report Using ASP.net Web Forms</h2>
 
<h3>Simple Report</h3>
@using (Html.BeginForm("ShowSimple", "Test_report"))
{
<input type="submit" value="Show simple" />
<input type="button" value="Show simple in New Window" onclick="SimpleInNewWin()"/>
<br />
}